spring.application.name=SwapTN_new
server.port=8081

# ===============================
# DATABASE CONNECTION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/SwapTN_new
spring.datasource.username=postgres
spring.datasource.password=11221122



# ===============================
# JPA / HIBERNATE
# ===============================

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional (shows SQL in console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Recommended
spring.jpa.open-in-view=false




jwt.secret=change-this-to-a-very-long-secret-key-for-hs256-signing-1234567890
jwt.expiration=86400000    
  #= 24 hours in milliseconds

app.upload.base-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=80MB



