spring.application.name=SwapTN_new
server.port=8081

# ===============================
# DATABASE CONNECTION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/swapTN_new
spring.datasource.username=postgres
spring.datasource.password=YEDESmehdi2005!
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional (shows SQL in console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Recommended
spring.jpa.open-in-view=false